In [2]:
import duckdb

ModuleNotFoundError: No module named 'duckdb'

In [3]:
pip install duckdb

Collecting duckdb
  Downloading duckdb-1.4.4-cp314-cp314-win_amd64.whl.metadata (4.3 kB)
Downloading duckdb-1.4.4-cp314-cp314-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.8 MB 16.7 MB/s eta 0:00:01
   --------------------------- ------------ 8.9/12.8 MB 21.2 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 20.1 MB/s  0:00:00
Installing collected packages: duckdb
Successfully installed duckdb-1.4.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [32]:
con = duckdb.connect(database = 'dados_duckdb.db', read_only = False)

In [23]:
arquivo = 'z0019_1.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100    100  z0019_1.csv 2026-02-26 16:02:46.170081
1  10002   MARTELO  BT50    100   1500  z0019_1.csv 2026-02-26 16:02:46.170081
2  10003     PREGO  BT10    100     50  z0019_1.csv 2026-02-26 16:02:46.170081

In [16]:
con.execute("""
   CREATE TABLE IF NOT EXISTS bronze_produtos (
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao TIMESTAMP
            )         
""")

In [19]:
con.execute("""INSERT INTO bronze_produtos SELECT * FROM df""")

In [20]:
resultado = con.execute("""SELECT * FROM bronze_produtos""").fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-02-26 15:49:32.961009
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-02-26 15:49:32.961009
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-02-26 15:49:32.961009

In [25]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df2 = pd.read_csv(f'../landing/{arquivo}', sep=';')
df2['nome_arquivo'] = arquivo
df2['data_ingestao'] = data_ingestao
df2.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-02-26 16:03:31.266319
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-02-26 16:03:31.266319
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-02-26 16:03:31.266319

In [28]:
con.execute("""INSERT INTO bronze_produtos SELECT * FROM df2""")

In [35]:
resultado = con.execute("""SELECT * FROM bronze_z0019""").fetchdf()
resultado

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-02-26 15:49:32.961009
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-02-26 15:49:32.961009
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-02-26 15:49:32.961009
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-02-26 16:03:31.266319
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-02-26 16:03:31.266319
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-02-26 16:03:31.266319

In [33]:
con.execute('ALTER TABLE bronze_produtos RENAME TO bronze_z0019')

In [31]:
con.close()