In [1]:
import duckdb

In [2]:
con = duckdb.connect(database = 'dados_duckdb.db', read_only = False)

In [10]:
df = con.execute(""" SELECT * FROM produtos""").fetchdf()

df

      id nm_produto Id_categoria  id_fornecedor  vl_preco
0  10004      SERRA         BT50            100     200.0
1  10003      PREGO         BT10            100      60.0
2  10001   PARAFUSO         BT10            100     100.0
3  10005    MACHADO         BT50            100     100.0
4  10002    MARTELO         BT50            100    1500.0

In [13]:
df2 = df2.drop(columns = ['id_categoria', 'id_fornecedor'])
df2

      id nm_produto  vl_preco
0  10004      SERRA     200.0
1  10003      PREGO      60.0
2  10001   PARAFUSO     100.0
3  10005    MACHADO     100.0
4  10002    MARTELO    1500.0

In [14]:
con.execute("""
    CREATE TABLE IF NOT EXISTS dim_produto (
            id BIGINT,
            nm_produto TEXT,
            vl_preco FLOAT
            )
""")

In [15]:
df_dim = con.execute(""" SELECT * FROM dim_produto""").fetchdf()

df_dim

Empty DataFrame
Columns: [id, nm_produto, vl_preco]
Index: []

In [16]:
con.execute("""
            INSERT INTO dim_produto
            SELECT * FROM df2
""")

In [17]:
df_dim = con.execute(""" SELECT * FROM dim_produto""").fetchdf()

df_dim

      id nm_produto  vl_preco
0  10004      SERRA     200.0
1  10003      PREGO      60.0
2  10001   PARAFUSO     100.0
3  10005    MACHADO     100.0
4  10002    MARTELO    1500.0

In [18]:
con.close()